services:
  reglab_test:
    image: reglab_test:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production  
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password="1234"
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/reglab_test.pfx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/https
    networks:
      - reglab_network
    depends_on:
      - redis
      - mongo

  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
    networks:
      - reglab_network

  mongo:
    image: "mongo:latest"
    container_name: "mongo"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=service_user_settings
      - MONGO_INITDB_ROOT_PASSWORD=service_user_settings
    ports:
      - "27017:27017"
    networks:
      - reglab_network
    volumes:
      - mongo_data:/data/db

networks:
  reglab_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local