services:
  reglab_test:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # Для разработки
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80:80"
    volumes:
      - ./certs:/https
      - ./app:/app
    networks:
      - reglab_network
    depends_on:
      - redis
      - mongo

networks:
  reglab_network:
    driver: bridge